#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 11 06:25:23 EDT 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fir_tb_func_synth -key {Post-Synthesis:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -view /home/ubuntu/caravel-soc_fpga-lab-main/lab-fir/fir_tb_behav.wcfg -log simulate.log"
xsim fir_tb_func_synth -key {Post-Synthesis:sim_1:Functional:fir_tb} -tclbatch fir_tb.tcl -view /home/ubuntu/caravel-soc_fpga-lab-main/lab-fir/fir_tb_behav.wcfg -log simulate.log

